# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog',
            field=models.CharField(choices=[('it', 'it'), ('moto', 'moto'), ('climbing', 'climbing'), ('guitar', 'guitar'), ('blob', 'blob')], default='blob', max_length=8),
        ),
    ]
